# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('num_stars', models.IntegerField()),
                ('num_users', models.IntegerField()),
            ],
        ),
    ]
